### ISSUE TITLE
Version in "./docker-compose.yml" is unsupported

### ISSUE THREAD

**Issue by W4nde3** [GZTimeWalker/CTF-nc-docker#8]
执行` python3 generate.py`时报错：
```
[!] Error occured, exiting...
```
在将`os.system('docker-compose --compatibility up --build -d')`中规避警告的`--compatibility`选项移除后出现出现如下警告：

![image](https://user-images.githubusercontent.com/45825507/159487546-59dd20c0-bb8d-485e-93bd-41403045cbf6.png)

由于`template/docker-compose.yml`文件中version字段值指定为`3.7`，可能导致执行某些较低版本的docker-compose时会出现异常（且此警告被--compatibility选项屏蔽掉）

我的docker-compose工具版本如下：
```
$ docker-compose version
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018

```

如果直接修改`template/docker-compose.yml`的版本为`"2.2" or "3.3"`并不会解决问题，因为不同版本的docker-compose.yml文件格式上有细微差别，貌似目前只能通过升级docker-compose工具来临时解决此问题。

**Comment by GZTimeWalker** [comment]
经过比对确认和测试，已将 `docker-compose.yml` 的版本降级为 `3.0`，这一举动能够使得绝大部分 `docker-compose` 可用。

不过仍然建议升级到更高版本的 `docker-compose` 和 Docker Engine。
